table d_CategoriaSimples
	lineageTag: 0943dd84-63fe-47e5-a6da-6d722a34c2af

	column Categoria
		dataType: string
		lineageTag: af3dc782-958c-4aa6-8b14-a083908ee69c
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Categoria Simples'
		dataType: string
		lineageTag: 20b355a6-e230-43a3-b248-2123e02e67f4
		summarizeBy: none
		sourceColumn: Categoria Simples

		annotation SummarizationSetBy = Automatic

	partition d_CategoriaSimples = m
		mode: import
		queryGroup: Dimensão
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8j28MiUzX0lHyUhPAcqO1YlWcq1ITS4tySwDyRjrKQSHhinoKyAEQUqcE3Mz8zLy81JLUhUCUosTUxKBak30IGyIkoD8gtKcxCKguCFQHMoBSQSXlhFnsE9qWSqGsc6JRemYlkG0HV6cj1tGQVfBOSOxuDgTQ4lvfglInykwEECs2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Categoria = _t, #"Categoria Simples" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Categoria", type text}, {"Categoria Simples", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

